### ISSUE TITLE
Version tags not automatically pushed

### ISSUE THREAD

**Issue by gigabo** [kittens/lerna#52]
Hi,

After each `lerna publish` I've found that I need to `git push origin <tag>`.

It _looks_ like this should happen automatically.  That's what the `--follow-tags` option is for, right?

I'm using the master branch of `lerna` (since `v1.1.0` doesn't actually work for me).

I'm on git version 2.6.2.

Thanks,

Bo

**Comment by thejameskyle** [comment]
> That's what the `--follow-tags` option is for, right?

It should, can you test out the `git push origin --follow-tags` on a test repo to see if it works for you?

> since v1.1.0 doesn't actually work for me

Why doesn't v1.1.0 work for you?

**Comment by hzoo** [comment]
The fact that master works and 1.1.0 doesn't is weird

**Comment by gigabo** [comment]
> can you test out the git push origin --follow-tags on a test repo to see if it works for you?

Will do.

> Why doesn't v1.1.0 work for you?

Fails thusly:

```
Checking packages...
fatal: No annotated tags can describe 'a3a40d6877e075527f3c069923dd7ecec06f24f6'.
However, there were unannotated tags: try --tags.

There was a problem publishing.
Error: Command failed: git describe a3a40d6877e075527f3c069923dd7ecec06f24f6
fatal: No annotated tags can describe 'a3a40d6877e075527f3c069923dd7ecec06f24f6'.
However, there were unannotated tags: try --tags.

    at checkExecSyncError (child_process.js:441:13)
    at Object.execSync (child_process.js:481:13)
    at execSync (/Users/bo/.nvm/versions/node/v4.2.3/lib/node_modules/lerna/lib/commands/updated.js:63:16)
    at exports.checkUpdatedPackages (/Users/bo/.nvm/versions/node/v4.2.3/lib/node_modules/lerna/lib/commands/updated.js:30:23)
    at Object.exports.execute (/Users/bo/.nvm/versions/node/v4.2.3/lib/node_modules/lerna/lib/commands/publish.js:27:23)
    at Object.<anonymous> (/Users/bo/.nvm/versions/node/v4.2.3/lib/node_modules/lerna/bin/lerna.js:41:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

**Comment by hzoo** [comment]
Ah `--tags`. I did that in https://github.com/kittens/lerna/pull/17 which was after

**Comment by gigabo** [comment]
> can you test out the git push origin --follow-tags on a test repo to see if it works for you?

`git push origin --follow-tags` didn't work on [my test repo](https://github.com/gigabo/bo-lerna-playground) either.  I had to push by hand.

Here's the full output from the two commands:

```
bo@bo:bo-lerna-playground (master)$ git push origin --follow-tags
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 278 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To git@github.com:gigabo/bo-lerna-playground.git
   9e25299..74200b2  master -> master
bo@bo:bo-lerna-playground (master)$ git push origin v0.0.1
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:gigabo/bo-lerna-playground.git
 * [new tag]         v0.0.1 -> v0.0.1
```

**Comment by gigabo** [comment]
> We could publish a 1.1.1 that's just with that extra commit

Yes, please. :)

**Comment by thejameskyle** [comment]
Hmm weird, that version of git *should* support `--follow-tags`, but I guess we can switch to two separate commands to ensure that they don't fail for anyone

**Comment by gigabo** [comment]
> I guess we can switch to two separate commands to ensure that they don't fail for anyone

How's [this](https://github.com/kittens/lerna/pull/54)?

**Comment by gigabo** [comment]
Been using https://github.com/kittens/lerna/pull/54 locally.  Does the trick for me.

**Comment by hzoo** [comment]
FYI, We published 1.1.1

**Comment by gigabo** [comment]
Thanks @hzoo.

**Comment by thejameskyle** [comment]
Moving to #54
