### ISSUE TITLE
Linking of Internal Packages Not Working in TravisCI

### ISSUE THREAD

**Issue by dtothefp** [kittens/lerna#87]
First referenced here https://github.com/kittens/lerna/issues/50 but @thejameskyle recommended this be a separate issue.

I have several packages that are linked/published by `lerna` https://github.com/dtothefp/build-boiler. I run `lerna bootstrap` on travis and it seems to complete successfully, but when I run my build task via `gulp` the internal packages that are "linked" by `lerna` cannot be found.

https://travis-ci.org/dtothefp/build-boiler/builds/116948869

<img width="1062" alt="screen shot 2016-03-18 at 1 45 22 pm" src="https://cloud.githubusercontent.com/assets/4656726/13886956/d666a66a-ed0f-11e5-842d-603d578c0026.png">
But upon running the build task in my module which depends upon some of my linked `packages` it seems the the `npm link` has failed

```
Error: Cannot find module '/home/travis/build/dtothefp/build-boiler/packages/boiler-utils'
```

**Comment by dtothefp** [comment]
After going through the `lerna bootstrap` code and seeing that is just writes a mock child module to the parent module's package.json I realized I made a dumb mistake and was not compiling my `packages/*/src` modules to `dist` before running `lerna bootstrap`. Dumb mistake so I'm closing this issue

**Comment by hzoo** [comment]
:+1: Yeah I think everyone assumes it is `npm linking` haha

**Comment by thejameskyle** [comment]
We really need to solve this problem...

**Comment by donmccurdy** [comment]
I'm struggling to get a Lerna repository set up with Travis CI as well. After trying various combinations, one subpackage or another always seems to not build. My project is https://github.com/donmccurdy/glTF-Transform, with the following running at the `before_script` step:

```
lerna bootstrap
lerna exec -- npm install
lerna link
npm run dist
```

Things fail in one of the first two steps. The `dist` script compiles all of the packages, and needs their dev and prod dependencies. Full logs are at https://travis-ci.com/donmccurdy/glTF-Transform/jobs/166066386, with the relevant excerpt below:

<details> 

<summary> Output</summary>

```
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install
lerna ERR! npm ERR! path /home/travis/build/donmccurdy/glTF-Transform/node_modules/.staging/@gltf-transform/ao-07510c7c/node_modules/@gltf-transform/core
lerna ERR! npm ERR! code ENOENT
lerna ERR! npm ERR! errno -2
lerna ERR! npm ERR! syscall rename
lerna ERR! npm ERR! enoent ENOENT: no such file or directory, rename '/home/travis/build/donmccurdy/glTF-Transform/node_modules/.staging/@gltf-transform/ao-07510c7c/node_modules/@gltf-transform/core' -> '/home/travis/build/donmccurdy/glTF-Transform/node_modules/.staging/@gltf-transform/core-d2cd2d50'
lerna ERR! npm ERR! enoent This is related to npm not being able to find a file.
lerna ERR! npm ERR! enoent 
lerna ERR! 
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /home/travis/.npm/_logs/2018-12-19T04_14_28_446Z-debug.log
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/home/travis/build/donmccurdy/glTF-Transform/node_modules/lerna/node_modules/execa/index.js:236:11)
{ Error: Command failed: npm install
npm ERR! path /home/travis/build/donmccurdy/glTF-Transform/node_modules/.staging/@gltf-transform/ao-07510c7c/node_modules/@gltf-transform/core
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/travis/build/donmccurdy/glTF-Transform/node_modules/.staging/@gltf-transform/ao-07510c7c/node_modules/@gltf-transform/core' -> '/home/travis/build/donmccurdy/glTF-Transform/node_modules/.staging/@gltf-transform/core-d2cd2d50'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-12-19T04_14_28_446Z-debug.log
    at Promise.all.then.arr (/home/travis/build/donmccurdy/glTF-Transform/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 254,
  killed: false,
  stdout: '',
  stderr:
   'npm ERR! path /home/travis/build/donmccurdy/glTF-Transform/node_modules/.staging/@gltf-transform/ao-07510c7c/node_modules/@gltf-transform/core\nnpm ERR! code ENOENT\nnpm ERR! errno -2\nnpm ERR! syscall rename\nnpm ERR! enoent ENOENT: no such file or directory, rename \'/home/travis/build/donmccurdy/glTF-Transform/node_modules/.staging/@gltf-transform/ao-07510c7c/node_modules/@gltf-transform/core\' -> \'/home/travis/build/donmccurdy/glTF-Transform/node_modules/.staging/@gltf-transform/core-d2cd2d50\'\nnpm ERR! enoent This is related to npm not being able to find a file.\nnpm ERR! enoent \n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/travis/.npm/_logs/2018-12-19T04_14_28_446Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm install',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ lerna:bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ lerna:bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-12-19T04_14_28_480Z-debug.log
The command "npm run lerna:bootstrap && npm run lerna:install && npm run lerna:link && npm run dist" failed and exited with 1 during .
```

</details>

**Comment by donmccurdy** [comment]
Go figure, I post here after a few hours of trying and then 10 minutes later get it working... 😅 In my case the issue was resolved by removing _all_ of the `package-lock.json` files, and simplying `before_script` to just:

```
lerna bootstrap
npm run dist
```

I also added `file:packages/foo` devDependencies to the root package.json, but I'm not sure whether that was part of the fix.
